version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - "5111:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: interview
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.1.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    command:
      - "start-dev"
  redis-server:
    image: 'redis'
    ports:
      - "6379:6379"